# Generated by Django 2.2 on 2021-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='story_teller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('storyteller', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='picture')),
                ('desc', models.TextField()),
            ],
        ),
    ]
