# Generated by Django 2.2 on 2021-12-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0002_auto_20211206_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story_teller',
            name='storyteller',
        ),
    ]
