# Generated by Django 2.2 on 2021-12-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0004_story_teller_storyteller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_teller',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
