# Generated by Django 2.2 on 2021-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0005_auto_20211207_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_teller',
            name='image',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
