# Generated by Django 2.2 on 2021-12-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0007_remove_story_teller_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='story_teller',
        ),
    ]
