# Generated by Django 2.2 on 2021-12-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0009_story_teller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_teller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
    ]
