# Generated by Django 2.2 on 2021-12-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0010_auto_20211207_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_teller',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
